### ISSUE TITLE
Support Webpack 4

### ISSUE THREAD

**Issue by HaNdTriX** [Milanzor/webpack-watched-glob-entries-plugin#1]
First of all thanks a lot for your webpack plugin 🙏.

**Issue:**

Using `webpack-watched-glob-entries-plugin` with webpack 4 currently doesn't work.
Are you already working on a solution or are you open for PRs?

**Error:**

```log
(node:11621) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Unhandled rejection TypeError: compilation.contextDependencies.concat is not a function
    at /Users/.../node_modules/webpack-watched-glob-entries-plugin/index.js:100:83
    
```

**Comment by Milanzor** [comment]
Definitely open for PR's! I havn't touched Webpack 4 yet, I will get to it soon and will update this plugin. If you can't wait and have a fix in mind, I'd be happy to review and merge it!

**Comment by Milanzor** [comment]
https://www.npmjs.com/package/webpack-watched-glob-entries-plugin Updated the NPM package to version 2.0.0
