### ISSUE TITLE
How to combine it with html-webpack-plugin to auto generate multiple html files?

### ISSUE THREAD

**Issue by CanRau** [Milanzor/webpack-watched-glob-entries-plugin#10]
Thanks to your plugin I can finally get more structure and automation in my current web-extension project where I need multiple entries and outputs
Next step would be to remove the manual .html files so the'll be autogenerated and styles and scripts can be injected by [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin)
I don't know how to let it figure out what files to generate. Only option I see at the moment would be to manually provide multiple HtmlWebpackPlugin, yet even then I don't know how to tell it which styles and scripts to inject.

Any hint would be great thanks a lot 🙏 

**Update** I tried to build a html-webpack-plugin plugin to alter the name based on the options but I can't get it working
```js
class MyPlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap('MyPlugin', compilation => {
      HtmlWebpackPlugin.getHooks(compilation).alterAssetTags.tapAsync(
        'MyPlugin', // <-- Set a meaningful name here for stacktraces
        (data, cb) => {
          // console.log(JSON.stringify(data, null, 2))
          data.assetTags.scripts = data.assetTags.scripts.filter(x =>
            x.attributes.src.includes(data.plugin.options.title)
          )
          data.assetTags.styles = data.assetTags.styles.filter(x =>
            x.attributes.href.includes(data.plugin.options.title)
          )
          data.outputName = `${data.plugin.options.title}/index.html`
          data.plugin.options.filename = `${data.plugin.options.title}/index.html`
          cb(null, data)
        }
      )
      HtmlWebpackPlugin.getHooks(compilation).beforeEmit.tapAsync(
        'MyPlugin',
        (data, cb) => {
          data.outputName = `${data.plugin.options.title}/index.html`
          data.plugin.options.filename = `${data.plugin.options.title}/index.html`
          cb(null, data)
        }
      )
    })
  }
}
```
I tried multiple ways I could think of^^ 
then in webpack config plugins
```js
[
  new HtmlWebpackPlugin({
    title: `popup`,
  }),
  new HtmlWebpackPlugin({
    title: `options`,
  }),
  new MyPlugin(),
]
```
That's probably better suited in the issues of `html-webpack-plugin` just mentioning here in case and to show that I tried "hard" 👷

**Comment by Milanzor** [comment]
I'm sorry, I don't know how to help you on this. This plugin is very 'dumb' in a way that it just takes globs in `entry` and returns the files represented by the globs. I do not see a way that it could be combined with the `html-webpack-plugin` in a way you want. 

I've not had a project with those requirements, so sorry, I'm not much of help.

Perhaps you can elaborate on your file structure and what file should load what other file?

Good luck!

**Comment by CanRau** [comment]
Thanks for the quick reply. Okay, all good it's not too bad just thought it might be cool to automate it away 😄 
Just wanted to post this on the html-webpack-plugin repo and this time I actually found existing discussions around that topic 😅haha
For reference: https://github.com/jantimon/html-webpack-plugin/issues/218 & [gwuhaolin/web-webpack-plugin](https://github.com/gwuhaolin/web-webpack-plugin)
Haven't tried anything else so far, I'm still using ne manual multi instance way..

Thanks again for your great plugin 🙏
