### ISSUE TITLE
Specify output name

### ISSUE THREAD

**Issue by mckittrick-kaminski-phx** [Milanzor/webpack-watched-glob-entries-plugin#22]
Thanks for the plugin, so far its working great for me.

I was curious is there was some way to specify the output. For my use case, I'm using the glob `./src/**/*.entry.tsx`. Right next to the `foo.entry.tsx` there are multiple regular `bar.ts` files that it consumes, but I want to signify the entrypoints by adding the `.entry.tsx` to the path. When it compiles, it places it in the build folder with `build/path/to/foo.entry`.

This'll work, worst case, but I'm looking to see if I can drop the `.entry`, such that the compile file turns into `build/path/to/foo`;

Thanks

**Comment by Milanzor** [comment]
Hi there!

I think you might want to look into the `output.filename` Webpack config option, over here: https://webpack.js.org/configuration/output/#outputfilename

This can be a string but also a function, within that function, you can probably strip off the `.entry`.
 
I'd be happy to help you further, but I don't think this plugin needs to provide you with the options to do so, I believe Webpack can already do it for you :)

Go ahead and make a bare-minimum reproduction repo and link it to me, I'd be happy to look at your config and see if I can get your result.

**Comment by mckittrick-kaminski-phx** [comment]
I looked, but I must have skimmed right over that one. I'll try this tomorrow and update/close this issue.

Thanks for your prompt reply!

**Comment by mckittrick-kaminski-phx** [comment]
Worked perfectly. I should stop yelling at my screen saying webpack devs are stupid for not including such a simple feature lmao.

Cheers.

**Comment by Milanzor** [comment]
Yelling at your screen is often a great way to make your code do what you want it to haha. Good luck!
