### ISSUE TITLE
Tests fail on Node 18.x (plugin might work though!)

### ISSUE THREAD

**Issue by Milanzor** [Milanzor/webpack-watched-glob-entries-plugin#28]
Because the tests fail on Node 18.x, I have limited the Node engine version to `>=12 <18`. The plugin will most probably still work. 

Please comment here if this causes you any inconvenience and I'll see if I can make some time to fix the failing test.

Or! You create PR and I'll merge it! :)

**Comment by KiKiKi-KiKi** [comment]
Hi, Are the errors that occurred in the test the this?

```sh
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
```

I upgraded `webpack` and `webpack-cli` versions like that, and this error does not occur.

```diff
    "devDependencies": {
         "chai": "^4.2.0",
         "mocha": "^10.0.0",
         "rimraf": "^3.0.2",
-        "webpack": "^5.11.1",
-        "webpack-cli": "^4.3.1"
+        "webpack": "^5.75.0",
+        "webpack-cli": "^5.0.1"
     },
```

I think the error is probably related to the old OpenSSL (OpenSSL 1.1.1 EOL).
cf. [Bringing forward the End-of-Life Date for Node.js 16](https://nodejs.org/en/blog/announcements/nodejs16-eol/)

Webpack v5.54.0 and later seem to fix this problem.

> There is a hashing algorithm that comes with Webpack v5.54.0+ that does not rely on OpenSSL.
> cf. https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported
