### ISSUE TITLE
[name] without directory

### ISSUE THREAD

**Issue by rickardliljeberg** [Milanzor/webpack-watched-glob-entries-plugin#3]
I would love if [name] would only contain the actual filename.
However I would also love to reach the path.

So if I have /scripts/clientName/whatever.scss
and I do the rule /scripts/**/*.scss

I would love if
[path] contained "clientName" (from my example)
and
[name] contained "whatever"

**Comment by Milanzor** [comment]
Sounds reasonable, I'm gonnna have look wether this is possible!

**Comment by rickardliljeberg** [comment]
For me right now having name without path in it would solve my issue.
So if not possible with the [path] portion maybe we could introduce a setting for if we want [name] with or without the path.

**Comment by Milanzor** [comment]
I've added an option to the entry function:

```
entry: WebpackWatchedGlobEntries.getEntries(
        // Globs
        [
            path.resolve(__dirname, 'src/**/*.js')
        ],

        // Glob options
        {},

        // Plugin options
        {
            basename_as_entry_name: true
        }
    ),

```

Using above config with the following directory structure:
- `src/some/file/here.js`
- `src/some/other/file/deeper/abc.js`

Will result in the following entries:
```
{
  'here.js': '/abs/path/to/src/some/file/here.js',
  'abc.js': '/abs/path/to/src/some/other/file/deeper/abc.js',
}
```

Make sure to update this package to 2.1 (I've updated the npm package)

**Comment by rickardliljeberg** [comment]
Great work, works like a charm and solves my problem!
