### ISSUE TITLE
How do I debug this? How do I merge this with an existing entry config?

### ISSUE THREAD

**Issue by nextgenthemes** [Milanzor/webpack-watched-glob-entries-plugin#31]
I just found out through painful trial and error that this returns an anonymous function. I was expecting a human readable object that Webpack takes as if I write the entries myself, apparently not.

`[Function (anonymous)]` is all I see on the console. How do I get already existing entries merged with the ones from this plugin? Or is this not possible?

```js
// does not work
config.entry = {
	...config.entry,
	...WebpackWatchedGlobEntries.getEntries( [
		resolve( projectDir, 'src/*.ts' ),
		resolve( projectDir, 'src/*.tsx' ),
		resolve( projectDir, 'src/ts/*.ts' ),
		resolve( projectDir, 'src/ts/*.tsx' ),
	] ),
};

// does work but not what I want.
config.entry = WebpackWatchedGlobEntries.getEntries( [
	resolve( projectDir, 'src/*.ts' ),
	resolve( projectDir, 'src/*.tsx' ),
	resolve( projectDir, 'src/ts/*.ts' ),
	resolve( projectDir, 'src/ts/*.tsx' ),
] );

log( '' );
log( config.entry );
log( '' );
```

**Comment by Milanzor** [comment]
Sorry for the late reply, I missed it. 

If you pass your `config.entry` as an element in the `getEntries` array, it'll be like a glob but it'll still work I presume.

If you need more assistance, please provide me with a reproduction example so I can help you through that.
