### ISSUE TITLE
Add Support for Node.js 22

### ISSUE THREAD

**Issue by massongit** [Milanzor/webpack-watched-glob-entries-plugin#36]
https://github.com/Milanzor/webpack-watched-glob-entries-plugin/blob/f4b7b42646269f5109ae5059ea701c404b264ead/package.json#L25

`webpack-watched-glob-entries-plugin` supports up to Node.js 21.
However, Node.js 22 becomes LTS since 2024-10-29: https://github.com/nodejs/Release
Therefore, I would be happy if this plugin supports Node.js 22.

**Comment by Milanzor** [comment]
There is a very high chance it'll run on Node 22.

I'm unavailable to do it myself this week but if you can make a PR, I can merge it and update this package.

Thanks
