### ISSUE TITLE
Release failed

### ISSUE THREAD

**Issue by massongit** [Milanzor/webpack-watched-glob-entries-plugin#41]
https://github.com/Milanzor/webpack-watched-glob-entries-plugin/actions/runs/12009043174/job/33472929405

The release of `v3.0.1` failed.
I think it will be successful if you reattach the `v3.0.1` tag to https://github.com/Milanzor/webpack-watched-glob-entries-plugin/commit/3255fbb7ec663d0c9cd949bc113b9dce92add460.

**Comment by Milanzor** [comment]
There's some more to do like an `npm pkg fix` but I'm out of offi e and can only do things from my phone.

I bumped it to 3.0.2 and all is good.

Thanks
