### ISSUE TITLE
Could you provide more control over the entries?

### ISSUE THREAD

**Issue by edygarOliveira** [Milanzor/webpack-watched-glob-entries-plugin#8]
Firstly, many thanks for this plugin, it was a life saver ;)

Now, could you provide more control over the `entry` instead of only `basename_as_entry_name `? (I could do the PR with retro-compatibility if you will)

For example: we could split [glob.sync callback](https://github.com/Milanzor/webpack-watched-glob-entries-plugin/blob/master/index.js#L88-L100) into two options: [getEntrynameFromFile](https://github.com/Milanzor/webpack-watched-glob-entries-plugin/blob/master/index.js#L89-L93) and a [transformEntry](https://github.com/Milanzor/webpack-watched-glob-entries-plugin/blob/master/index.js#L96), defaulting them to their current implementation

**Comment by Milanzor** [comment]
Hey, that sounds like a great idea. Go ahead :)
